---
themes:
  default:
    fg: [169,177,214] #A9B1D6
    bg: [26,27,38] #1A1B26
    black: [56,62,90] #383E5A
    red: [249,51,87] #F9334D
    green: [158,206,106]  #9ECE6A
    yellow: [224,175,104] #E0AF68
    blue: [122,162,247]  #7AA2F7
    magenta: [187,154,247] #BB9AF7
    cyan: [42,195,222] #2AC3DE
    white: [192,202,245] #C0CAF5
    orange: [255,158,100] #FF9E64
keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'x',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'e',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'z',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right ]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up, ]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
        - action: [GoToTab: 1]
          key: [ Alt: '1',]
        - action: [GoToTab: 2]
          key: [ Alt: '2',]
        - action: [GoToTab: 3]
          key: [ Alt: '3',]
        - action: [GoToTab: 4]
          key: [ Alt: '4',]

    locked:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'x',]
    resize:
        - action: [Resize: Left,]
          key: [Char: 'h', Left,]
        - action: [Resize: Down,]
          key: [Char: 'j', Down,]
        - action: [Resize: Up,]
          key: [Char: 'k', Up, ]
        - action: [Resize: Right,]
          key: [Char: 'l', Right,]
        - action: [Resize: Increase,]
          key: [Char: '=']
        - action: [Resize: Increase,]
          key: [ Char: '+']
        - action: [Resize: Decrease,]
          key: [Char: '-']
        - action: [SwitchToMode: Normal,]
          key: [Char: "\n", Char: ' ', Esc]
    pane:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'p', Char: "\n", Char: ' ', Esc]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [SwitchFocus,]
          key: [Char: 'p']
        - action: [NewPane: , SwitchToMode: Normal,]
          key: [Char: 'n',]
        - action: [NewPane: Down, SwitchToMode: Normal,]
          key: [Char: 'd',]
        - action: [NewPane: Right, SwitchToMode: Normal,]
          key: [Char: 'r',]
        - action: [CloseFocus, SwitchToMode: Normal,]
          key: [Char: 'x',]
        - action: [ToggleFocusFullscreen, SwitchToMode: Normal,]
          key: [Char: 'f',]
        - action: [TogglePaneFrames, SwitchToMode: Normal,]
          key: [Char: 'z',]
        - action: [ToggleFloatingPanes, SwitchToMode: Normal,]
          key: [Char: 'e']
        - action: [TogglePaneEmbedOrFloating, SwitchToMode: Normal,]
          key: [Char: 'w']
        - action: [SwitchToMode: RenamePane, PaneNameInput: [0],]
          key: [Char: 'c']
    move:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'h', Char: "\n", Char: ' ', Esc]
        - action: [Quit]
          key: [Ctrl: 'q']
        - action: [MovePane: ,]
          key: [Char: 'n', Char: "\t",]
        - action: [MovePane: Left,]
          key: [Char: 'h', Left,]
        - action: [MovePane: Down,]
          key: [Char: 'j', Down,]
        - action: [MovePane: Up,]
          key: [Char: 'k', Up, ]
        - action: [MovePane: Right,]
          key: [Char: 'l', Right,]
    renametab:
        - action: [SwitchToMode: Normal,]
          key: [Char: "\n", Ctrl: 'c', Esc]
        - action: [TabNameInput: [27] , SwitchToMode: Tab,]
          key: [Esc,]
    renamepane:
        - action: [SwitchToMode: Normal,]
          key: [Char: "\n", Ctrl: 'c', Esc]
        - action: [PaneNameInput: [27] , SwitchToMode: Pane,]
          key: [Esc,]
    tmux:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'o', Char: "\n", Char: ' ', Esc]
        - action: [NewPane: Down, SwitchToMode: Normal,]
          key: [Char: "\"",]
        - action: [NewPane: Right, SwitchToMode: Normal,]
          key: [Char: '%',]
        - action: [ToggleFocusFullscreen, SwitchToMode: Normal,]
          key: [Char: 'z',]
        - action: [NewTab: , SwitchToMode: Normal,]
          key: [ Char: 'c',]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: ',']
        - action: [SwitchToMode: RenamePane, PaneNameInput: [0],]
          key: [Char: '.']
        - action: [GoToPreviousTab, SwitchToMode: Normal,]
          key: [ Char: 'p']
        - action: [GoToNextTab, SwitchToMode: Normal,]
          key: [ Char: 'n']
        - action: [Detach,]
          key: [Char: 'd',]
plugins:
    - path: tab-bar
      tag: tab-bar
    - path: status-bar
      tag: status-bar
    - path: strider
      tag: strider
    - path: compact-bar
      tag: compact-bar
